### ISSUE TITLE
Slow down when approaching the boundary wire

### ISSUE THREAD

**Issue by MagnusPer** [Selective031/RazorBoard#10]
The mower I have has fallen over border with the help of a slope. If the mower sense the border is approaching and slows down in advance it will solve those situations.

**Comment by Selective031** [comment]
Its a good feature, maybe we can have a signal magnitude check. However will also slow down if it is near and running along the perimeter wire?

**Comment by Selective031** [comment]
I have a working concept of this now, with almost centimeter precision.

**Comment by Selective031** [comment]
This function is now included in the "dev" branch, please test it. I have also added some documentation in the readme file "Proximity Magnitude"

**Comment by Selective031** [comment]
This has been implemented now, function is called "Proximity Magnitude". Will be included in the next release.
