### ISSUE TITLE
Overturn security feature is not active during perimeter tracking

### ISSUE THREAD

**Issue by danielerikhansson** [Selective031/RazorBoard#11]
The overturn security feature is not enabled during perimeter tracking, this might be minor since the cutter is not in use regardless - but still considered good if the mower stops completely if someone would lift it up even during the going home phase. 

My suggestion is to move the overturn check from `checkState()` to `checkSecurity()` and return `SECURITY_FAIL` when an overturn has been detected. Then the security feature it provides would be active regardless of the state the mower is currently in.

**Comment by Selective031** [comment]
I agree, overturn check should be active at all times.

**Comment by Selective031** [comment]
This has been implemented and verified. Will be included in next release.
