### ISSUE TITLE
Store of failures in SRAM

### ISSUE THREAD

**Issue by MagnusPer** [Selective031/RazorBoard#13]
To ease the fault tracing to understanding why the mower stopped/tripped etc. The ~20 latest reported failures should be stored to SRAM. The data to store should include at least the type of failure and when it happened, preferable also the value of the data that triggered the failure  

Example
`<date><time><failure type><state><data>`

```
<2021-05-05 19:26> <OUTSIDE> <STOP>
<2021-06-10 20:10> <MOTOR M1 CURRENT> <2.3 AMP> <FORWARD> 
```

The list of failures should be readable via a command using the COM port

**Comment by Selective031** [comment]
This is nearly complete, Razorboard now has 20 lines with 50 characters (1000 bytes) each of messages stored in SRAM, which is retained during power cycles.
Commands:
"show errors"  - will simply show a list of messages, the newest is at the bottom (scroll style)
"clear errors" - will erase the whole list
"add error" - will add a test error message to the list

**Comment by Selective031** [comment]
Released
