### ISSUE TITLE
Limit current consumption settings for the motors to not exceed HW limitation  

### ISSUE THREAD

**Issue by MagnusPer** [Selective031/RazorBoard#18]
The HW itself is protected but there is no way software vise to take actions if the settings is above the tolerance of the hardware. The software configuration parameter should then have a max below the HW tolerance.

**Comment by Selective031** [comment]
What should the limit do? and should the limit be applied to the resistor limit or the peak limit of hardware?

**Comment by MagnusPer** [comment]
You have correct, I was more in to protect persons not having the knowledge about the hardware limitation. I have instead complemented the settings description with this information 

https://github.com/Selective031/RazorBoard/wiki/01.--Settings
