### ISSUE TITLE
Some commands are missing in the help menu

### ISSUE THREAD

**Issue by MagnusPer** [Selective031/RazorBoard#27]
Check the available commands and update help menu. Example are SHOW ERRORS and CLEAR ERRORS

**Comment by MagnusPer** [comment]
Remove ADC level since this not is used anymore

**Comment by Selective031** [comment]
The two missing commands are now added in the latest commit.
Lets keep ADC level for now, maybe we can move it to some advanced menu. 
One though is to separate the different commands into sub-menus, like motors, bwf, battery etc... to make it even easier to find correct commands.
