### ISSUE TITLE
High grass detection 

### ISSUE THREAD

**Issue by MagnusPer** [Selective031/RazorBoard#4]
The current functionality is the following 

`If the current is too high on the cutting disk, it will HARDBREAK and STOP, until reset by the user.`

This is most likely because of high grass and I suggest instead to turn off the cutter motor, drive away and restart the cutter again. If the current is still high after X retries then HARDBREAK and STOP and report failure HIGH GRASS

**Comment by Selective031** [comment]
Agreed, the "current to high" limit is more if you hit something and the cutting disk it hitting an hard object, we don´t want to hurt anyone or risking the disk/motor/shaft to break. We could pass the value from the sensor into an array and calculate the average value for about 20-50 values or so, then detect if its hard for the disk to spin and take some action.

**Comment by Selective031** [comment]
A new function is being tested.
When the high grass is detected, the mower will do:
MotorStop
MotorBackward
Wait 2 sec (to allow the cutter to speed up again)
Go forward slowly
if high grass is detected again, it will start over
if not, the mower will go forward slowly for 10 sec, then speed up to normal speed again.

**Comment by Selective031** [comment]
Released
