### ISSUE TITLE
Spinning detection 

### ISSUE THREAD

**Issue by MagnusPer** [Selective031/RazorBoard#6]
If the mower stands still but the motors is running the mower is stuck. The proposal is to use the Gyro to detect the movement where the mower should try by redirect the move direction several times in different directions till it moves again. If several retries doesn't help then HANDBREAK and STOP and report a failure MOWER STUCK

**Comment by Selective031** [comment]
Good suggestion!

**Comment by MagnusPer** [comment]
Clarification to my comment about using the Gyro, to solve this the accelerometer functionality in the MPU6050 is needed to be used.

**Comment by Selective031** [comment]
Yes, that is understood.

**Comment by Selective031** [comment]
I solution has been committed to dev branch, just need to verify and test it a bit before moving to main.
