### ISSUE TITLE
Separate configuration file

### ISSUE THREAD

**Issue by MagnusPer** [Selective031/RazorBoard#8]
Instead of rebuilding the project when change/test some configuration values a separate config file should be super!

**Comment by Selective031** [comment]
This is about to be released, all functions are already done. Only thing I need to add are what settings should be presented to the user. Also, if the board doesn´t detect any settings (like powering up for the first time) it will automatically save default config.

**Comment by Selective031** [comment]
The first version of this was released in 1.0.1, more to come...

**Comment by MagnusPer** [comment]
I have tested the configuration introduced in 1.0.1 version. Well done!
For me OK to set this to done

**Comment by Selective031** [comment]
Perfect. closing this.
